# -*- coding: utf-8 -*-
"""4120E014.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tqrPWwa-Akt0V2IkdXIs10vHH67Ubt1W
"""

3**2